version: "2"

networks:
  web:
    external: true

services:
  mongodb:
    restart: always 
    image: mongo:latest
    ports:
      - 27017:27017
    env_file:
      - .env
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:
